trigger:
- main

pool:
  name: Digital-Ocean

variables:
- group: DIGITAL-OCEAN

stages:
- stage: CreateDroplet
  jobs:
    - steps:
        - script: |
            terraform init 
          displayName: 'Terraform init'
        - script: |
            terraform plan -var "TOKEN=$TOKEN"
          displayName: 'Terraform plan'
        - script: |
            terraform apply -auto-approve -var "TOKEN=$TOKEN"
          displayName: 'Terraform Apply'